# Generated by Django 5.1.6 on 2025-03-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='account_number',
            field=models.CharField(default='PL61109010140000071219812874', max_length=255),
        ),
    ]
