# Generated by Django 5.1.6 on 2025-03-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
