# Generated by Django 5.1.6 on 2025-03-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_slug_remove_expense_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'verbose_name_plural': 'transaction types'},
        ),
    ]
