# Generated by Django 5.1.6 on 2025-03-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_transactiontype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'verbose_name_plural': 'transaction_types'},
        ),
    ]
